seed_everything: 1234
ckpt_path: null # to resume

trainer:
  fast_dev_run: false
  accelerator: gpu
  # strategy: ddp # or ddp_find_unused_parameters
  devices: [0]
  accumulate_grad_batches: 4
  num_nodes: 1
  precision: bf16 # or 32, or 16
  max_epochs: 50
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 10
  log_every_n_steps: 50

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "./output/probe.HookTheoryKey.MuQ/checkpoints/" # Please specify your own path
        filename: "best"
        save_top_k: 1 # -1 to save all checkpoints
    - class_path: marble.modules.callbacks.LoadLatestCheckpointCallback # for testing
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: "val/weighted_score"               # 要监控的 metric 名称
        patience: 10                       # 在多少次验证后无改进就停止
        mode: "max"                       # “val_loss” 下降时才算改进
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "marble"
      name: "probe.HookTheoryKey.MuQ"
      save_dir: "./output/probe.HookTheoryKey.MuQ/"


model:
  class_path: marble.tasks.HookTheoryKey.probe.ProbeAudioTask
  init_args:
    sample_rate: 24000
    use_ema: false

    encoder:
      class_path: marble.encoders.MuQ.model.MuQ_Encoder
      init_args:
        pre_trained_folder: null
        train_mode: freeze  # also supports lora, or full
      
    emb_transforms:
      - class_path: marble.modules.transforms.MLPReduce
        init_args:
          num_layers: 13
          hidden_size: 1024
    
    decoders:
      - class_path: marble.modules.decoders.MLPDecoder
        init_args:
          in_dim: 1024
          out_dim: 24 # 24 KEYS
          hidden_layers: [512]
          activation_fn: 
            class_path: torch.nn.ReLU
          dropout: 0.2

    losses:
      - class_path: torch.nn.CrossEntropyLoss
        init_args:
          reduction: mean

    metrics:
      train:
        acc:
          class_path: torchmetrics.Accuracy
          init_args:
            num_classes: 24
            task: multiclass
        weighted_score:
          class_path: marble.tasks.HookTheoryKey.probe.KeyWeightedScore
      val:
        acc:
          class_path: torchmetrics.Accuracy
          init_args:
            num_classes: 24
            task: multiclass
        weighted_score:
          class_path: marble.tasks.HookTheoryKey.probe.KeyWeightedScore
      test:
        acc:
          class_path: torchmetrics.Accuracy
          init_args:
            num_classes: 24
            task: multiclass
        weighted_score:
          class_path: marble.tasks.HookTheoryKey.probe.KeyWeightedScore
    
data:
  class_path: marble.tasks.HookTheoryKey.datamodule.HookTheoryKeyDataModule
  init_args:
    batch_size: 16
    num_workers: 16

    train:
      class_path: marble.tasks.HookTheoryKey.datamodule.HookTheoryKeyAudioTrain
      init_args:
        sample_rate: 24000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.8 # at least 80% of the clip length
        channel_mode: random # first, random, mix
        jsonl: data/HookTheory/HookTheoryKey.train.jsonl
        maj_minor_only: true # only use major and minor keys
    val:
      class_path: marble.tasks.HookTheoryKey.datamodule.HookTheoryKeyAudioVal
      init_args:
        sample_rate: 24000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.8
        channel_mode: mix
        jsonl: data/HookTheory/HookTheoryKey.val.jsonl
        maj_minor_only: true # only use major and minor keys
    test:
      class_path: marble.tasks.HookTheoryKey.datamodule.HookTheoryKeyAudioTest
      init_args:
        sample_rate: 24000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.8
        channel_mode: mix
        jsonl: data/HookTheory/HookTheoryKey.test.jsonl
        maj_minor_only: true # only use major and minor keys

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1e-3

lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    mode: "max"
    factor: 0.1
    patience: 5
    monitor: "val/weighted_score"
