seed_everything: 1234
ckpt_path: null # to resume

trainer:
  fast_dev_run: false
  accelerator: gpu
  # strategy: ddp # or ddp_find_unused_parameters
  devices: [0]
  accumulate_grad_batches: 4
  num_nodes: 1
  precision: bf16 # or 32, or 16
  max_epochs: 100
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 10
  log_every_n_steps: 5

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "./output/probe.EMO.Qwen2AudioInstructEncoder/checkpoints/" # Please specify your own path
        filename: "best"
        save_top_k: 1 # -1 to save all checkpoints
    - class_path: marble.modules.callbacks.LoadLatestCheckpointCallback # for testing
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: "val/r2"               # 要监控的 metric 名称
        patience: 20                       # 在多少次验证后无改进就停止
        mode: "max"                       # “val_loss” 下降时才算改进
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "marble"
      name: "probe.EMO.Qwen2AudioInstructEncoder"
      save_dir: "./output/probe.EMO.Qwen2AudioInstructEncoder/"


model:
  class_path: marble.tasks.EMO.probe.ProbeAudioTask
  init_args:
    sample_rate: 16000
    use_ema: false

    encoder:
      class_path: marble.encoders.Qwen2AudioInstructEncoder.model.Qwen2AudioInstructEncoder
      init_args:
        pre_trained_folder: null
        train_mode: freeze  # also supports lora, or full
        attn_implementation: sdpa  # or sdpa, or flash_attention_2
      
    emb_transforms:
      - class_path: marble.modules.transforms.LayerSelector
        init_args:
          layers: [32]  # something like [1, 3, "10..72"]
      - class_path: marble.modules.transforms.TimeAvgPool # (batch_size, num_layers, 1, hidden_size)
    
    decoders:
      - class_path: marble.modules.decoders.MLPDecoder
        init_args:
          in_dim: 1280
          out_dim: 2 # 2 genres
          hidden_layers: [512]
          activation_fn: 
            class_path: torch.nn.ReLU
          dropout: 0.2

    losses:
      # regression
      - class_path: torch.nn.MSELoss
        init_args:
          reduction: mean

    metrics:
      train:
        r2:
          class_path: torchmetrics.R2Score
          init_args:
            multioutput: uniform_average
        arousal_r2:
          class_path: marble.tasks.EMO.probe.SliceR2
          init_args:
            dim: 0
        valence_r2:
          class_path: marble.tasks.EMO.probe.SliceR2
          init_args:
            dim: 1
      val:
        r2:
          class_path: torchmetrics.R2Score
          init_args:
            multioutput: uniform_average
        arousal_r2:
          class_path: marble.tasks.EMO.probe.SliceR2
          init_args:
            dim: 0
        valence_r2:
          class_path: marble.tasks.EMO.probe.SliceR2
          init_args:
            dim: 1
      test:
        r2:
          class_path: torchmetrics.R2Score
          init_args:
            multioutput: uniform_average
        arousal_r2:
          class_path: marble.tasks.EMO.probe.SliceR2
          init_args:
            dim: 0
        valence_r2:
          class_path: marble.tasks.EMO.probe.SliceR2
          init_args:
            dim: 1
    
data:
  class_path: marble.tasks.EMO.datamodule.EMODataModule
  init_args:
    batch_size: 16
    num_workers: 8

    audio_transforms:
      train:
        - class_path: marble.encoders.Qwen2AudioInstructEncoder.model.Qwen2AudioInstructFeatureExtractor
          init_args:
            pre_trained_folder: null
      val:
        - class_path: marble.encoders.Qwen2AudioInstructEncoder.model.Qwen2AudioInstructFeatureExtractor
          init_args:
            pre_trained_folder: null
      test:
        - class_path: marble.encoders.Qwen2AudioInstructEncoder.model.Qwen2AudioInstructFeatureExtractor
          init_args:
            pre_trained_folder: null

    train:
      class_path: marble.tasks.EMO.datamodule.EMOAudioTrain
      init_args:
        sample_rate: 16000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.8 # at least 80% of the clip length
        channel_mode: first # first, random, mix
        jsonl: data/EMO/EMO.train.jsonl
    val:
      class_path: marble.tasks.EMO.datamodule.EMOAudioVal
      init_args:
        sample_rate: 16000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.8
        channel_mode: first
        jsonl: data/EMO/EMO.val.jsonl
    test:
      class_path: marble.tasks.EMO.datamodule.EMOAudioTest
      init_args:
        sample_rate: 16000
        channels: 1
        clip_seconds: 15
        min_clip_ratio: 0.8
        channel_mode: first
        jsonl: data/EMO/EMO.test.jsonl

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1e-3

lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    mode: "max"
    factor: 0.5
    patience: 6
    monitor: "val/r2"
